Import modules

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

Read the dataset

In [2]:
dataset = pd.read_csv('train.csv')

In [3]:
dataset

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

Preprocessing

In [5]:
x=dataset.drop(labels=["label"],axis=1) 
y=dataset["label"]

In [6]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

Split the dataset into Training and Test

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [9]:
x_train

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
5837        0       0       0       0       0       0       0       0       0   
26919       0       0       0       0       0       0       0       0       0   
15177       0       0       0       0       0       0       0       0       0   
14046       0       0       0       0       0       0       0       0       0   
22315       0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41993       0       0       0       0       0       0       0       0       0   
32103       0       0       0       0       0       0       0       0       0   
30403       0       0       0       0       0       0       0       0       0   
21243       0       0       0       0       0       0       0       0       0   
2732        0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
5837        0  ...         0         0         0         0         0   
26919       0  ...         0         0         0         0         0   
15177       0  ...         0         0         0         0         0   
14046       0  ...         0         0         0         0         0   
22315       0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41993       0  ...         0         0         0         0         0   
32103       0  ...         0         0         0         0         0   
30403       0  ...         0         0         0         0         0   
21243       0  ...         0         0         0         0         0   
2732        0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
5837          0         0         0         0         0  
26919         0         0         0         0         0  
15177         0         0         0         0         0  
14046         0         0         0         0         0  
22315         0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41993         0         0         0         0         0  
32103         0         0         0         0         0  
30403         0         0         0         0         0  
21243         0         0         0         0         0  
2732          0         0         0         0         0  

[31500 rows x 784 columns]

In [10]:
y_train

5837     1
26919    8
15177    9
14046    7
22315    2
        ..
41993    6
32103    1
30403    9
21243    0
2732     9
Name: label, Length: 31500, dtype: int64

In [11]:
x_test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
16275       0       0       0       0       0       0       0       0       0   
19204       0       0       0       0       0       0       0       0       0   
18518       0       0       0       0       0       0       0       0       0   
25780       0       0       0       0       0       0       0       0       0   
16228       0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27825       0       0       0       0       0       0       0       0       0   
14840       0       0       0       0       0       0       0       0       0   
3916        0       0       0       0       0       0       0       0       0   
24730       0       0       0       0       0       0       0       0       0   
38244       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
16275       0  ...         0         0         0         0         0   
19204       0  ...         0         0         0         0         0   
18518       0  ...         0         0         0         0         0   
25780       0  ...         0         0         0         0         0   
16228       0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27825       0  ...         0         0         0         0         0   
14840       0  ...         0         0         0         0         0   
3916        0  ...         0         0         0         0         0   
24730       0  ...         0         0         0         0         0   
38244       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
16275         0         0         0         0         0  
19204         0         0         0         0         0  
18518         0         0         0         0         0  
25780         0         0         0         0         0  
16228         0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27825         0         0         0         0         0  
14840         0         0         0         0         0  
3916          0         0         0         0         0  
24730         0         0         0         0         0  
38244         0         0         0         0         0  

[10500 rows x 784 columns]

In [12]:
y_test

16275    3
19204    6
18518    9
25780    5
16228    6
        ..
27825    5
14840    8
3916     4
24730    0
38244    5
Name: label, Length: 10500, dtype: int64

Normalozation

In [13]:
x_train = x_train.astype('float32')/255.0
x_test = x_test.astype('float32')/255.0

SVM Model

In [14]:
svm = SVC(kernel='rbf',random_state=0)
svm.fit(x_train,y_train)
y_pred = svm.predict(x_test)
acc_svm = svm.score(x_test,y_test)
print(acc_svm*100)

C:\Users\pc\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


93.71428571428572


Confusion Matrix

In [16]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 986    0    0    4    5    5    8    0    7    0]
 [   0 1170    7    2    1    3    2    0    3    2]
 [   6    4  998   13   14    3   14    9   15    1]
 [   4    5   18  970    1   36    6    9   13    8]
 [   2    4    4    0  974    1   10    3    0   36]
 [   2    8    1   18   10  869   13    0    7    2]
 [   6    1    6    0    4    9 1015    0    3    0]
 [   4   10   20    3   18    1    0 1045    2   26]
 [   5   10    8   21    5   30   13    3  892    8]
 [  12    4    4   10   24    4    2   30    5  921]]
